[package]
name = "barge"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
errs = { version = "0.1", path = "../errs"}
parking_lot = "0.12"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
strum = { version = "0.24", features = ["derive"] }
